CREATE TYPE "public"."event_type" AS ENUM('theater', 'fair', 'festival', 'concert', 'exhibition', 'food_and_drinks', 'movie_screening', 'workshop', 'party', 'other');--> statement-breakpoint
CREATE TABLE "agendas" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agendas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"url" text NOT NULL,
	"venue_id" bigint,
	"has_detail_urls" boolean DEFAULT true
);
--> statement-breakpoint
CREATE TABLE "event_occurrences" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_occurrences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"event_id" bigint NOT NULL,
	"occurs_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"event_type" "event_type" NOT NULL,
	"title" text NOT NULL,
	"summary" text NOT NULL,
	"description" text NOT NULL,
	"free_admission" boolean NOT NULL,
	"registration_required" boolean,
	"from_price" double precision,
	"sold_out" boolean,
	"image_url" text,
	"venue_details" text,
	"venue_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "venues" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "venues_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"street_address" text NOT NULL,
	"url" text NOT NULL,
	"logo_url" text
);
--> statement-breakpoint
ALTER TABLE "agendas" ADD CONSTRAINT "agendas_venue_id_venues_id_fk" FOREIGN KEY ("venue_id") REFERENCES "public"."venues"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_occurrences" ADD CONSTRAINT "event_occurrences_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_venue_id_venues_id_fk" FOREIGN KEY ("venue_id") REFERENCES "public"."venues"("id") ON DELETE no action ON UPDATE no action;